### ISSUE TITLE
Lazy loading in highlight.js may break some languages highlighting

### ISSUE THREAD

**Issue by microdog** [hexojs/hexo-util#25] opened 2017-05-09 15:30 UTC
Hello,
The lazy loading behavior in `lib/highlight.js` introduced in  7f6469e1bd83abc56f23414ce92fe84f13bc9a88 may break some languages highlighting such as `shell`.

The [`shell`](https://github.com/isagalaev/highlight.js/blob/master/src/languages/shell.js) language highlighting relies on the [`bash`](https://github.com/isagalaev/highlight.js/blob/master/src/languages/bash.js) language, if `bash` language is not registered yet, you will get an unexpected highlighting result.

Input:
```js
var str = '$ echo "Hello World"';
```

Expected result:
```js
'<span class="meta">$</span><span class="bash"> <span class="built_in">echo</span> <span class="string">"Hello World"</span></span>'
```

Only `shell` is registered:
```js
'<span class="meta">$</span> echo "Hello World"'
```

**Comment by alxbl** [comment] 2017-12-11 23:52
I'm able to reproduce this behavior as well.

When testing, make sure to use `hexo server -s` combined with `hexo generate` to serve the static content, otherwise it looks like `loadAllLanguages` is called and the issue does not happen.

That being said, I doubt that there's much that hexo can do besides systematically load all languages.

The workaround right now would be to leave out the language from the code block and set `highlight.autoDetect: true` in your config file.

Another possible workaround could be to have a hidden/draft post that has an empty code block for each language that you will use. This should force the generator to require those languages, and then you shouldn't have any problems in the actual post.

Cheers,

**Comment by curbengh** [comment] 2019-09-14 08:27
Is this a sublanguage highlight issue? Is it fixed by https://github.com/hexojs/hexo-util/pull/37?

**Comment by stevenjoezhang** [comment] 2020-04-26 07:36
Fixed by https://github.com/hexojs/hexo-util/pull/192
Please enable `highlight.auto_detect` in Hexo `_config.yml`

**Closed by stevenjoezhang** 2020-04-26 07:36 UTC
Labels: help wanted, need-verify
