### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Nonage** [hexojs/hexo-util#20] opened 2016-12-17 19:58 UTC
─ns@ns-HP-Pavilion-Notebook ~  
╰─➤  sudo npm install -g hexo-cli                                                        1 ↵
/usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo-cli/bin/hexo

> dtrace-provider@0.8.0 install /usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider
> node scripts/install.js

sh: 1: node: not found
npm WARN install:dtrace-provider@0.8.0 dtrace-provider@0.8.0 install: `node scripts/install.js`
npm WARN install:dtrace-provider@0.8.0 spawn ENOENT

> hexo-util@0.6.0 postinstall /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-util
> npm run build:highlight

> hexo-util@0.6.0 build:highlight /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

sh: 1: node: not found

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:highlight"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hexo-util@0.6.0 build:highlight: `node scripts/build_highlight_alias.js > highlight_alias.json`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.0 build:highlight script 'node scripts/build_highlight_alias.js > highlight_alias.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hexo-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build_highlight_alias.js > highlight_alias.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexo-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hexo-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-util/npm-debug.log
/usr/local/lib
└── (empty)

npm WARN optional Skipping failed optional dependency /hexo-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "hexo-cli"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! hexo-util@0.6.0 postinstall: `npm run build:highlight`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.0 postinstall script 'npm run build:highlight'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hexo-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:highlight
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexo-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hexo-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ns/npm-debug.log
npm ERR! code 1

> _****_

**Comment by Nonage** [comment] 2016-12-17 20:02
[npm-debug.txt](https://github.com/hexojs/hexo-util/files/659061/npm-debug.txt)

**Comment by NoahDragon** [comment] 2016-12-17 21:41
Could you please elaborate? Which command output these errors?

**Comment by Nonage** [comment] 2016-12-19 13:47
一装就报错啊。nodejs npm git 都有的

**Comment by NoahDragon** [comment] 2016-12-19 14:42
这一般不是hexo的问题，基本是nodejs/npm环境配置。

**Comment by demurgos** [comment] 2017-10-26 08:11
This issue is also a duplicate of this one with more info: https://github.com/hexojs/hexo-util/issues/24

(I guess it can be closed)

**Closed** 2017-10-27 14:19 UTC
